#!/usr/bin/python
import sys

def doRename(line):
    parts = line.split(" ")
    keeper = None
    for p in parts:
        if "sf" in p and "(" in p:
            keeper = p.split("(")[0]
    cName = keeper.replace("*", "")
    goName = cName.replace("_", "")[2:]

    rename = "%" + "rename(%s) %s;" % (goName, cName)
    return rename

print "//generated by mangler.py"
for line in sys.stdin:
    if len(line) < 5: continue
    print doRename(line)
    print line




#%rename(ImageCreateFromFile) sfImage_CreateFromFile;
